name: Publish Docker

on:
  schedule:
    - cron: '45 10 * * 1'
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build builder image
    steps:
      - name: Checkout master
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Build and publish image
        uses: ilteoood/docker_buildx@master
        with:
          publish: true
          imageName: guixi/ympd
          platform: linux/arm/v7,linux/amd64,linux/arm64
          dockerUser: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerPassword: ${{ secrets.DOCKERHUB_TOKEN }}
